spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?useSSL=false
    username: root
    password:
    sql-script-encoding: UTF-8
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    user: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/school?useSSL=false
    locations: classpath:db/migration
    schemas: school
    baseline-on-migrate: false
    validate-on-migrate: true